site_name: Speak to Me
site_url: https://speak.wntr.dev
repo_url: "https://github.com/wntrblm/Speak_to_Me"
edit_uri: edit/main/user_guide/docs
theme:
    name: wintersong
plugins: []
markdown_extensions:
    - abbr
    - admonition
    - def_list
    - attr_list
    - footnotes
    - md_in_html
    - toc:
          permalink: "#"
          toc_depth: 2-2
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.blocks.tab:
          alternate_style: true
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
          hide_protocol: true
          repo_url_shortener: true
          social_url_shortener: true
          normalize_issue_symbols: true
          repo_url_shorthand: true
          user: wntrblm
          repo: winter
    - pymdownx.mark
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
nav:
    - "Manual": index.md
    - "Build": build.md
