name: Docs
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "user_guide/**"
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install dependencies
              run: |
                  python3.12 -m pip install -r user_guide/requirements.txt
            - name: MkDocs publish
              run: mkdocs gh-deploy --force
              working-directory: user_guide
